
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jan 19 2024 12:00:08 IST (Jan 19 2024 06:30:08 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21;
  DFFQX1 \count_reg[7] (.CK (clk), .D (n_21), .Q (count[7]));
  NOR2XL g243__2398(.A (rst), .B (n_19), .Y (n_21));
  DFFQX1 \count_reg[6] (.CK (clk), .D (n_20), .Q (count[6]));
  NOR2XL g247__5107(.A (rst), .B (n_18), .Y (n_20));
  AOI21XL g245__6260(.A0 (count[7]), .A1 (n_17), .B0 (n_16), .Y (n_19));
  DFFQX1 \count_reg[5] (.CK (clk), .D (n_15), .Q (count[5]));
  OAI21XL g249__4319(.A0 (n_14), .A1 (count[6]), .B0 (n_17), .Y (n_18));
  NOR2XL g246__8428(.A (count[7]), .B (n_17), .Y (n_16));
  DFFQX1 \count_reg[4] (.CK (clk), .D (n_13), .Q (count[4]));
  AOI211XL g251__5526(.A0 (n_12), .A1 (n_11), .B0 (rst), .C0 (n_14), .Y
       (n_15));
  NOR2XL g254__6783(.A (rst), .B (n_10), .Y (n_13));
  NAND2XL g250__3680(.A (count[6]), .B (n_14), .Y (n_17));
  DFFQX1 \count_reg[3] (.CK (clk), .D (n_9), .Q (count[3]));
  NOR2XL g253__1617(.A (n_12), .B (n_11), .Y (n_14));
  OAI21XL g256__2802(.A0 (count[4]), .A1 (n_8), .B0 (n_11), .Y (n_10));
  DFFQX1 \count_reg[2] (.CK (clk), .D (n_7), .Q (count[2]));
  AOI211XL g258__1705(.A0 (n_5), .A1 (n_6), .B0 (rst), .C0 (n_8), .Y
       (n_9));
  NOR2XL g261__5122(.A (rst), .B (n_4), .Y (n_7));
  NAND2XL g257__8246(.A (count[4]), .B (n_8), .Y (n_11));
  DFFQX1 \count_reg[1] (.CK (clk), .D (n_3), .Q (count[1]));
  NOR2XL g260__7098(.A (n_6), .B (n_5), .Y (n_8));
  OAI21X1 g263__6131(.A0 (count[2]), .A1 (n_2), .B0 (n_5), .Y (n_4));
  NOR3X1 g265__1881(.A (rst), .B (n_1), .C (n_2), .Y (n_3));
  NAND2XL g264__5115(.A (count[2]), .B (n_2), .Y (n_5));
  DFFQX1 \count_reg[0] (.CK (clk), .D (n_0), .Q (count[0]));
  AND2X1 g267__7482(.A (count[1]), .B (count[0]), .Y (n_2));
  NOR2XL g268__4733(.A (count[0]), .B (count[1]), .Y (n_1));
  NOR2XL g269__6161(.A (rst), .B (count[0]), .Y (n_0));
  CLKINVX1 g270(.A (count[3]), .Y (n_6));
  CLKINVX1 g271(.A (count[5]), .Y (n_12));
endmodule

